"""update book table

Revision ID: 5b2c895c8ca9
Revises: 
Create Date: 2026-04-21 11:22:11.906772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2c895c8ca9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('publication_info', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('isbn'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('isbn'), ['isbn'], unique=True)
        batch_op.drop_column('publication_info')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
