"""update code

Revision ID: b51c9a313511
Revises: dda20940403d
Create Date: 2026-05-09 22:54:40.985032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51c9a313511'
down_revision = 'dda20940403d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_report', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
